### ISSUE TITLE
Youtube name

### ISSUE THREAD

**Issue by matthiaswuyts** [PatrickAcheson/automate_youtube_shorts#1]
Whats your yt channel

**Comment by PatrickAcheson** [comment]
https://youtu.be/lulRRKY3Jzc?si=ur6VBAjN-dyerYmd

**Comment by matthiaswuyts** [comment]
> https://youtu.be/lulRRKY3Jzc?si=ur6VBAjN-dyerYmd

Thanks altough it didnt work for me still getting an error

C:\Users\MatthiasW609\Downloads\automate_youtube_shorts-main\automate_youtube_shorts-main>python main.py
Traceback (most recent call last):
  File "C:\Users\MatthiasW609\Downloads\automate_youtube_shorts-main\automate_youtube_shorts-main\main.py", line 7, in <module>
    from upload_video import upload
  File "C:\Users\MatthiasW609\Downloads\automate_youtube_shorts-main\automate_youtube_shorts-main\upload_video.py", line 17
    options.add_argument("user-data-dir=C:\Users\MatthiasW609\AppData\Local\Google\Chrome Beta\User Data\Default") #change

                                                 ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 16-17: truncated \UXXXXXXXX escape

C:\Users\MatthiasW609\Downloads\automate_youtube_shorts-main\automate_youtube_shorts-main>

**Comment by matthiaswuyts** [comment]
> 

i fixed it but now when i run it nothing shows up or runs

**Comment by PatrickAcheson** [comment]
Hey, I am going to have a look tonight at the code it was working fine, then people started getting issues. For now I'd ask chat gpt.

**Comment by matthiaswuyts** [comment]
Well yeah now i type python main.py and it just doesnt do anything so the error is fixed but yeah

**Comment by matthiaswuyts** [comment]
> Well yeah now i type python main.py and it just doesnt do anything so the error is fixed but yeah

What i did find out when i stopped running the code was that it says time.sleep(1)

**Comment by PatrickAcheson** [comment]
Have you removed the scheduler and tried just calling the main function?

**Comment by matthiaswuyts** [comment]
> Have you removed the scheduler and tried just calling the main function?

Now i have and now i'm getting a huge error with the instagram thing

**Comment by PatrickAcheson** [comment]
I'm gonna ask a dumb question, but have you pip installed the requirements? But yeah I'll have a  look at it soon.

**Comment by matthiaswuyts** [comment]
> I'm gonna ask a dumb question, but have you pip installed the requirements? But yeah I'll have a look at it soon.

Very dumb question hahah yes i did i will check again if i put in the right pass and username

**Comment by matthiaswuyts** [comment]
> > I'm gonna ask a dumb question, but have you pip installed the requirements? But yeah I'll have a look at it soon.
> 
> Very dumb question hahah yes i did i will check again if i put in the right pass and username

JSON Query to accounts/login/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
JSON Query to accounts/login/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
Traceback (most recent call last):
  File "C:\Users\MatthiasW609\AppData\Local\Programs\Python\Python311\Lib\site-packages\instaloader\instaloadercontext.py", line 357, in get_json
    raise QueryReturnedNotFoundException("Could not find \"window._sharedData\" in html response.")
instaloader.exceptions.QueryReturnedNotFoundException: Could not find "window._sharedData" in html response.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MatthiasW609\AppData\Local\Programs\Python\Python311\Lib\site-packages\instaloader\instaloadercontext.py", line 357, in get_json
    raise QueryReturnedNotFoundException("Could not find \"window._sharedData\" in html response.")
instaloader.exceptions.QueryReturnedNotFoundException: Could not find "window._sharedData" in html response.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MatthiasW609\AppData\Local\Programs\Python\Python311\Lib\site-packages\instaloader\instaloadercontext.py", line 357, in get_json
    raise QueryReturnedNotFoundException("Could not find \"window._sharedData\" in html response.")
instaloader.exceptions.QueryReturnedNotFoundException: Could not find "window._sharedData" in html response.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\MatthiasW609\Downloads\automate_youtube_shorts-main\automate_youtube_shorts-main\main.py", line 38, in <module>
    run_job(length, output_dir, download_dir)
  File "C:\Users\MatthiasW609\Downloads\automate_youtube_shorts-main\automate_youtube_shorts-main\main.py", line 18, in run_job
    download(length)
  File "C:\Users\MatthiasW609\Downloads\automate_youtube_shorts-main\automate_youtube_shorts-main\download_insta.py", line 17, in download
    ig.login("designsmatters", "secret")  # change this :)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MatthiasW609\AppData\Local\Programs\Python\Python311\Lib\site-packages\instaloader\instaloader.py", line 634, in login
    self.context.login(user, passwd)
  File "C:\Users\MatthiasW609\AppData\Local\Programs\Python\Python311\Lib\site-packages\instaloader\instaloadercontext.py", line 214, in login
    csrf_json = self.get_json('accounts/login/', {}, session=session)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MatthiasW609\AppData\Local\Programs\Python\Python311\Lib\site-packages\instaloader\instaloadercontext.py", line 395, in get_json
    return self.get_json(path=path, params=params, host=host, session=sess, _attempt=_attempt + 1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MatthiasW609\AppData\Local\Programs\Python\Python311\Lib\site-packages\instaloader\instaloadercontext.py", line 395, in get_json
    return self.get_json(path=path, params=params, host=host, session=sess, _attempt=_attempt + 1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MatthiasW609\AppData\Local\Programs\Python\Python311\Lib\site-packages\instaloader\instaloadercontext.py", line 383, in get_json
    raise QueryReturnedNotFoundException(error_string) from err
instaloader.exceptions.QueryReturnedNotFoundException: JSON Query to accounts/login/: Could not find "window._sharedData" in html response.
This is the huge error pass and username are all right so idk what to do. ChatGPT can't help either

**Comment by PatrickAcheson** [comment]
Yeah I see the issue, I will work on it now.

**Comment by matthiaswuyts** [comment]
> Yeah I see the issue, I will work on it now.

Alr ty

**Comment by PatrickAcheson** [comment]
I updated instaloader now I am getting this error: https://stackoverflow.com/questions/76824230/json-query-to-accounts-login-could-not-find-window-shareddata-in-html-respo

**Comment by PatrickAcheson** [comment]
Looks like Instagram have updated and Instaload is broken.

**Comment by matthiaswuyts** [comment]
> Looks like Instagram have updated and Instaload is broken.

So we just wait? and see what happens?

**Comment by PatrickAcheson** [comment]
Might try see if i can get this to work - https://www.geeksforgeeks.org/download-instagram-reel-using-python/

**Comment by matthiaswuyts** [comment]
> Might try see if i can get this to work - https://www.geeksforgeeks.org/download-instagram-reel-using-python/

Alr

**Comment by PatrickAcheson** [comment]
I mean good news is they might update instaloader soon and fix it.

**Comment by matthiaswuyts** [comment]
> I mean good news is they might update instaloader soon and fix it.

Good to hear

**Comment by matthiaswuyts** [comment]
> I mean good news is they might update instaloader soon and fix it.

Do you even need to follow those accounts you put in accounts.txt or not?
